指摘して頂いた箇所を修正しました。
youlimx/BattleofFantasista pull request #3
Opened 2022-01-13 07:53 UTC by youlimx

publicを[SerializeField]に変更する部分と、分かりやすい定数を定義するように修正しました。

2022-01-13 08:31 UTC, inokinn commented on Assets/Script/EnemyHealth.cs
> +    int enemyHP;
[SerializeField] と変数定義は同じ行に記述可能です。
とはいえ改行するかどうかは（プロジェクト内でルールが決まってない限りは）好みの問題なので、同じ行にするか改行するかはお任せします。
（知っててこうしてるか、知らなかったかだけ気になりました）

2022-01-13 08:35 UTC, inokinn commented on Assets/Script/EnemySpawner.cs
> +    private float _spawnTimer = 0.0f;
変数名にアンダースコアが付いているものと付いていないものがありますが、何かルールはありますか？
もしあるのであれば、すべてのファイルにそのルールを適用してほしいです。

C# だと、一般的には private なメンバ変数にアンダースコアを付けるという慣例が多いようですね。

2022-01-13 08:36 UTC, inokinn commented on Assets/Script/EnemySpawner.cs
> +    private const int SpawnInterval = 1.0f;
定数にはコメントで「この定数が何を表すのか」を書いておいた方がよいです

2022-01-13 08:39 UTC, inokinn commented on Assets/Script/EnemySpawner.cs
> +    private float _spawmRandomMin = -25.0f;
この辺も定数にしちゃってよいと思います

2022-01-13 08:40 UTC, inokinn requested changes
一通り気になった点をコメントしました。

2022-01-14 02:10 UTC, youlimx commented on Assets/Script/EnemyHealth.cs
> +    int enemyHP;
年末年始に読んだUnityの本で[SerializeField]の所は改行して書いてあったのでそれと同じように書きました。
正直、同じ行のほうが見やすいのにな～って思ってたので、そっちにします！

2022-01-14 02:12 UTC, youlimx commented on Assets/Script/EnemySpawner.cs
> +    private float _spawnTimer = 0.0f;
すみません、間違えてました。
修正します。

2022-01-14 02:13 UTC, youlimx commented on Assets/Script/EnemySpawner.cs
> +    private const int SpawnInterval = 1.0f;
分かりました！

2022-01-14 02:13 UTC, youlimx commented on Assets/Script/EnemySpawner.cs
> +    private float _spawmRandomMin = -25.0f;
分かりました！

2022-01-14 05:23 UTC, inokinn requested changes

2022-01-14 05:23 UTC, inokinn commented on Assets/Script/EnemyHealth.cs
> +    [SerializeField]AudioClip breakSound;
細かいですが、ここだけ `[SerializeField]` と `AudioClip` の間にスペース無いのが気になりました

2022-01-14 05:23 UTC, inokinn commented on Assets/Script/EnemySpawner.cs
> +    private const float _spawnTimer = 0.0f;
これを定数にしちゃうと値を変えられなくてエラーになる気がしますが、コミット前にビルドや動作確認をしましたか？

2022-01-14 05:23 UTC, inokinn commented on Assets/Script/EnemySpawner.cs
> +    private const float _spawnInterval = 1.0f;
定数の命名規則として、アンダースコアを付けたという感じですかね？
あまり見ないケースだと思うのと、 C# 的には大文字開始がメジャーだと思うので、変数の命名規則について他の事例を見たり、一般的な慣習を調べてみるとよいかもしれません。

2022-01-14 05:23 UTC, inokinn commented on Assets/Script/FireBeam.cs
>      bool onSpace = false;
public / private は明示的に書いておいた方がいいかもです。
デフォルト private なので慣れれば省略しても問題ないですが、最初のうちはメンバ変数の public / private は意識してみてください（SerializeField なやつは private なことが自明なので、そこまではいらないですが）。

2022-01-14 05:23 UTC, inokinn commented on Assets/Script/PlayerScript.cs
>      AudioSource audioSource;
ここも、public /private は書いておいた方がよいですね

2022-01-14 05:52 UTC, youlimx commented on Assets/Script/EnemyHealth.cs
> +    [SerializeField]AudioClip breakSound;
見落としてました…
修正しておきます

2022-01-14 05:53 UTC, youlimx commented on Assets/Script/EnemySpawner.cs
> +    private const float _spawnTimer = 0.0f;
確認してなかったです…
修正しておきます

2022-01-14 05:57 UTC, youlimx commented on Assets/Script/EnemySpawner.cs
> +    private const float _spawnInterval = 1.0f;
privateだったのでアンダースコア付けてました！定数だと違うんですね…
調べてみます！

2022-01-14 05:58 UTC, youlimx commented on Assets/Script/FireBeam.cs
>      bool onSpace = false;
分かりました！

2022-01-14 05:59 UTC, youlimx commented on Assets/Script/PlayerScript.cs
>      AudioSource audioSource;
分かりました！修正しておきます！

2022-01-14 08:54 UTC, inokinn commented on Assets/Script/EnemySpawner.cs
> +    private const float _spawnInterval = 1.0f;
> privateだったのでアンダースコア付けてました！

他のファイルではこのルールになっていなかったので、定数だから付けてるのかな、と思ってしまいました。
コーディングルールは全てのファイルに適用してほしいですー

2022-01-14 10:20 UTC, inokinn requested changes

2022-01-14 10:20 UTC, inokinn commented on Assets/Script/EnemyHealth.cs
> +    AudioSource _audioSource;
これも `private` ですね
（類似の指摘点は他の部分もチェックしてもらえると幸いです）

2022-01-14 10:20 UTC, inokinn commented on Assets/Script/EnemyScript.cs
> +    float _speed = 8.0f;
この変数は利用していますか？
（利用していない変数は即座に消しておいた方が後で混乱しなくて楽です）

2022-01-14 10:20 UTC, inokinn commented on Assets/Script/EnemySpawner.cs
> +    private const float SpawnRandomMax = 25.0f;
変数定義の並び順にも意識した方がよさそうです。
定数の中に変数が混ざっており、後で見つけにくいので。

一例ですが、↓みたく public なものから順にならべていくとか。
```
public int hogehoge;
public string fugafuga;

[SerializeField] int _hp;
[SerializeField] GameObject _someObject;

private const float Cat = 1.0f;
private const float Dog = -25.0f;
private const float  Rabbit = 25.0f;

private int _currentHp;
private string _name;
private float _timer = 0.0f;
```

2022-01-14 10:20 UTC, inokinn commented on Assets/Script/GameManager.cs
>      int count;
ここも private 必要ですね

2022-01-14 10:20 UTC, inokinn commented on Assets/Script/PlayerScript.cs
>              int damage = 1;
ここって 1 を変数 damage に入れてる理由ありますか？
代入して 93 行目で 1 回だけ参照されているだけに見えるので、 damage 変数はいらないのかなと
（一方で、これがダメージを表すということが文脈的に分かりやすくはあったので、定数にするなど工夫してもいいかもですね）

2022-01-14 10:20 UTC, inokinn commented on Assets/Script/PlayerScript.cs
>          if (collider.gameObject.tag == "Enemy")
Button() 関数がだいぶ肥大化してきましたね。
ダメージ処理は独立した関数に切り出した方がよさそうです。

2022-01-14 13:44 UTC, ystekitou commented on Assets/Script/EnemySpawner.cs
> +    private const int SpawnInterval = 1.0f;
今回のケースではコメントだけで良いですが、
定数をインスペクターに表示したい場合(つまり、[SerializeField] const ~~の場合)にはコメントだけではなくて、[Header]や[Tooltip]も併用してインスペクター上にコメントが出るようにしておくのが良いですね。

2022-01-14 13:47 UTC, ystekitou commented on Assets/Script/EnemySpawner.cs
>          }
この辺りはメソッドにしておいた方が良いですね。
敵の生成条件が今は時間だけですが、他でも生成したい場合が出てきそうです。

2022-01-17 06:30 UTC, youlimx commented on Assets/Script/EnemyHealth.cs
> +    AudioSource _audioSource;
分かりました！

2022-01-17 06:45 UTC, youlimx commented on Assets/Script/EnemyScript.cs
> +    float _speed = 8.0f;
使ってないので消しておきます！

2022-01-17 06:47 UTC, youlimx commented on Assets/Script/EnemySpawner.cs
> +    private const float SpawnRandomMax = 25.0f;
分かりました！

2022-01-17 06:55 UTC, youlimx commented on Assets/Script/GameManager.cs
>      int count;
分かりました！

2022-01-17 07:03 UTC, youlimx commented on Assets/Script/PlayerScript.cs
>              int damage = 1;
後でダメージの値変えるかもしれないので作ってました。定数に変えておきます。

2022-01-17 07:23 UTC, youlimx commented on Assets/Script/PlayerScript.cs
>          if (collider.gameObject.tag == "Enemy")
分かりました！

2022-01-17 07:32 UTC, youlimx commented on Assets/Script/EnemySpawner.cs
>          }
分かりました！

2022-01-20 06:57 UTC, inokinn requested changes

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/EnemyHealth.cs
> +        // hpSlider.value = enemyHP;
コメントアウトしたコードは消した方がよいです

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/EnemyHealth.cs
> +    //private void OnCollisionStay(Collision col)
同上

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/EnemyHealth.cs
> +    private int trans;
これも `trans` にすべきですかね？
あとメンバ変数の役割を変数名から推察できないので、コメントで役割を書いておくことをオススメします。
こんな感じで
```
    [SerializeField] private int _enemyHP;             // エネミーのHP
    [SerializeField] private Slider _hpSlider;         // エネミーのHPのスライダー
    [SerializeField] private Animator _anim;           // アニメータ
    [SerializeField] private AudioClip _breakSound;    // 変数の説明
```

（見たところ、 `OnCollisionEnter(Collision col)` 関数で `1` が代入されているだけで使われてない？）

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/EnemySpawner.cs
> +    [SerializeField] private GameObject _enemy;
この変数にも、この下でやってるのと同様にコメントで説明を入れてあげるとよいです

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/EnemySpawner.cs
> +    void Spawner()
関数名に違和感がありますね。
`Spawner` は名詞ですが、関数は一般的に「機能」の名前になるので、動詞になることが多いです。
この場合だと `Spawn()` でしょうか。
または、クラス名が `EnemySpawner` なので「 Spawn させる役割」であることは自明なので、 `execute()` や `exec()` などでもこの場合は OK だと思います。

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/FireBeam.cs
> +    [SerializeField] private GameObject _beamPrefab;
このあたりもコメントで役割を書いてあげるとよいです。
慣れないうちは特に、メンバ変数にコメントで説明を書いておくと、役割を整理する助けになります。

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/FireBeam.cs
> +    void Start()
不要な関数は消しておいた方がよいですね

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/FireBeam.cs
> +    private bool _onSpace = false;
`_onSpace` という命名は役割に対して正しいですか？

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/FireBeam.cs
> +            _onSpace = true;
このフラグはいつ `false` になるのでしょうか

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/GameManager.cs
> +    private int count;
これも変数名にアンダースコア付けたほうがよいですね

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/GameManager.cs
> +    public void Score()
関数名と実態が合ってないように見えますね。
以下のようにすると、敵ごとにスコアを設定したりと汎用性の高い使い方ができそうです。
```
public void AddSAcore(int value)
{
    count += value;
}
```

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/GameManager.cs
> +    private int count;
あと、 `count` だと名前がふわっとしすぎていて、何をカウントしているのか変数名から分からないので、再考した方がよさそうです。
スコアを表す数値なので `_score` でよさそう。

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/PlayerScript.cs
> +   void OnMove(InputValue input)
このあたりは「何をする関数か」というコメントがほしいですね

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/PlayerScript.cs
> +    void Damage()
これも関数名は `ReceiveDamage()` みたいな感じの方がよさそう

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/PlayerScript.cs
> +    public static IEnumerator AttackVibrate(float duration = 0.1f, float frequency = 1.0f, float amplitude = 1.0f, OVRInput.Controller controller = OVRInput.Controller.Active)
この関数、 `PlayerScript` クラスと `RightArmScript` クラスの両方に全く同じ処理がありますが、共通化できませんか
？

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/PlayerScript.cs
> +    public static IEnumerator AttackVibrate(float duration = 0.1f, float frequency = 1.0f, float amplitude = 1.0f, OVRInput.Controller controller = OVRInput.Controller.Active)
コントローラを振動させたりする処理は `Player` の責務ではないので、どこに置くかは議論の余地がありますが、一旦 `GameManager` とかでも良いような気はします。

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/RightArmScript.cs
> +        _gameManager = GameObject.Find("GameManager");
`GameManager` は MonoBehaviour なので、 `Find` しなくても [SerializeField] で入れてあげた方がよいです

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/RightArmScript.cs
> +    private GameManager _script;
`_script` という変数名は非常に抽象的なので、何のスクリプトなのかわかる変数名の方がよいです

2022-01-20 06:57 UTC, inokinn commented on Assets/Script/TimerScript.cs
> +        GetComponent<Text>().text = _countTime.ToString("F2"); //����2���ɂ��ĕ\��
`Update()` 関数の中で `GetComponent` するのは処理に多大な負荷がかかるのでやめた方がいいです

2022-01-21 02:59 UTC, youlimx commented on Assets/Script/EnemyHealth.cs
> +        // hpSlider.value = enemyHP;
後で使うつもりなのですが、消した方がいいですか？

2022-01-21 02:59 UTC, youlimx commented on Assets/Script/EnemyHealth.cs
> +    //private void OnCollisionStay(Collision col)
こっちは消しておきます！

2022-01-21 03:14 UTC, youlimx commented on Assets/Script/EnemyHealth.cs
> +    private int trans;
コメントアウトのご指摘の所でもですが、HPスライダーは最初は付けていたのですが、一時期、テストするときに敵が死んだら面倒なので外していました。今は敵が死ぬのは必要なのでそれは書いていますが、HPバーは最終的に付ければいいので後回しにしています。デザイナーに作ってもらう予定もあるので…。使わないときは完全に取り除いた方がいいですか？

2022-01-21 03:23 UTC, youlimx commented on Assets/Script/EnemySpawner.cs
> +    [SerializeField] private GameObject _enemy;
分かりました！

2022-01-21 03:27 UTC, youlimx commented on Assets/Script/EnemySpawner.cs
> +    void Spawner()
分かりました！

2022-01-21 03:43 UTC, youlimx commented on Assets/Script/FireBeam.cs
> +    [SerializeField] private GameObject _beamPrefab;
分かりました！

2022-01-21 05:26 UTC, youlimx commented on Assets/Script/FireBeam.cs
> +    void Start()
分かりました！

2022-01-21 05:27 UTC, youlimx commented on Assets/Script/FireBeam.cs
> +    private bool _onSpace = false;
スペースキーを押したかどうかの判定です。
_pushSpaceの方が分かりやすそうなので変えておきます。

2022-01-21 05:28 UTC, youlimx commented on Assets/Script/FireBeam.cs
> +            _onSpace = true;
ビームが切れた時です。修正しておきます。

2022-01-21 06:17 UTC, youlimx commented on Assets/Script/GameManager.cs
> +    private int count;
分かりました！

2022-01-21 06:43 UTC, youlimx commented on Assets/Script/GameManager.cs
> +    public void Score()
分かりました！

2022-01-21 06:50 UTC, youlimx commented on Assets/Script/PlayerScript.cs
> +   void OnMove(InputValue input)
分かりました！

2022-01-21 06:53 UTC, youlimx commented on Assets/Script/PlayerScript.cs
> +    void Damage()
分かりました！

2022-01-21 07:48 UTC, youlimx commented on Assets/Script/PlayerScript.cs
> +    public static IEnumerator AttackVibrate(float duration = 0.1f, float frequency = 1.0f, float amplitude = 1.0f, OVRInput.Controller controller = OVRInput.Controller.Active)
GameManagerにAttackVibrateを移して、PlayerScriptでAttackVibrateを呼び出したら
「インスタンス参照でメンバーにアクセスできません。代わりに型名を使用してください」っていうエラーが出たのですがよく分からないです。

2022-01-21 08:24 UTC, youlimx commented on Assets/Script/RightArmScript.cs
> +        _gameManager = GameObject.Find("GameManager");
分かりました！

2022-01-21 08:25 UTC, youlimx commented on Assets/Script/RightArmScript.cs
> +    private GameManager _script;
分かりました！

2022-01-21 08:31 UTC, youlimx commented on Assets/Script/TimerScript.cs
> +        GetComponent<Text>().text = _countTime.ToString("F2"); //����2���ɂ��ĕ\��
分かりました！
ゲームのルールが変わって、制限時間が無しになったので、もう要らないので消しておきます。

2022-01-28 06:30 UTC, inokinn commented on Assets/Script/EnemyHealth.cs
> +    private int trans;
> HPバーは最終的に付ければいいので後回しにしています。デザイナーに作ってもらう予定もあるので…。

であれば、その旨をコメントアウトで併記してもらえるとありがたいです。
その背景はコードからでは読み取れないので、使わなくなったゴミが残っているのか一時的に封じているのかがわからないので…。

2022-01-28 06:33 UTC, inokinn commented on Assets/Script/TimerScript.cs
> +        GetComponent<Text>().text = _countTime.ToString("F2"); //����2���ɂ��ĕ\��
ちなみに、なぜ高負荷になってしまうのかというと、
`GetComponent` はコンポーネントを検索する処理を行うので、その中で走査が行われます（なのでなかなか処理負荷が高い）。
で、 `Update()` 関数は毎フレーム実行される関数なので、1フレームごとにいちいちコンポーネントを検索することになり、結果的に膨大な負荷となるのです

2022-01-31 09:40 UTC, inokinn requested changes

2022-01-31 09:40 UTC, inokinn commented on Assets/Script/EnemyHealth.cs
> +        // hpSlider.value = enemyHP;
後で使うのであれば、その旨をコメントとして残しておいてほしいです

2022-01-31 09:40 UTC, inokinn commented on Assets/Script/PlayerScript.cs
> +            StartCoroutine(AttackVibrate(0.1f, 1.0f, 1.0f, controller: OVRInput.Controller.RTouch)) ;
`StartCoroutine(AttackVibrate(0.1f, 1.0f, 1.0f, controller: OVRInput.Controller.RTouch)) ;`
と
```
    public static IEnumerator AttackVibrate(float duration, float frequency, float amplitude, OVRInput.Controller controller = OVRInput.Controller.Active)
    {
        //コントローラーを振動させる
        OVRInput.SetControllerVibration(frequency, amplitude, controller);

        //指定された時間待つ
        yield return new WaitForSeconds(duration);

        //コントローラーの振動を止める
        OVRInput.SetControllerVibration(0, 0, controller);
    }
```

が複数存在するので、これだけなんとかしたいですね。
「コントローラを振動させる」ことは Player という概念の責務ではないので、一旦 `GameManager` あたりに担当させるとよいと思います。
コルーチンと、コルーチンを開始する関数を `GameManager` に生やして、利用側はそれを呼び出す形にするとよいかもです。

2022-02-02 07:38 UTC, youlimx commented on Assets/Script/PlayerScript.cs
> +            StartCoroutine(AttackVibrate(0.1f, 1.0f, 1.0f, controller: OVRInput.Controller.RTouch)) ;
分かりました！

2022-02-04 06:03 UTC, inokinn approved these changes
1点だけコメントしました。
この部分だけ解決したらマージしてよいと思います。

2022-02-04 06:03 UTC, inokinn commented on Assets/Script/PlayerScript.cs
> +    private GameManager _gameManager;
`RightArmScript` では GameManager を SerializeField で取得している一方で、こちらのクラスでは GetComponent で取得している理由はありますか？
特に無ければ、 SerializeField で統一してもよいかもしれません。

2022-02-05 05:50 UTC, youlimx commented on Assets/Script/PlayerScript.cs
> +    private GameManager _gameManager;
分かりました！

2022-02-05 06:11 UTC, merged